### ISSUE TITLE
KeyError: 'cycle_index'

### ISSUE THREAD

**Issue by ymxka** [microsoft/BatteryML#46]
Hi,
Thanks for open source this interesting project.
I have downloaded and preprocessed the MATR dataset, but I encountered an issue while converting the data to BatteryData, as shown in the third image. Do I need to convert the mat files to csv files, or is there another solution to this problem?

<img width="555" alt="MATR_data" src="https://github.com/user-attachments/assets/f1777cb2-d160-490e-996c-de18e0ebdba2">
<img width="541" alt="Processed_Data" src="https://github.com/user-attachments/assets/6d818d5f-4a7d-4368-9e20-9b5ac04c4aa8">
<img width="1197" alt="BatteryData_Issue" src="https://github.com/user-attachments/assets/80d3a15b-d860-4755-b7a8-52b7c81d98c5">

**Comment by opqrst-chen** [comment]
Hello,  
   
Thank you for raising this issue and for your interest in our project.  
   
Regarding the handling of the MATR dataset, we have a separate implementation. 

You can refer to the following commands to preprocess the `MATR dataset of ".mat" file type`:  
   
```bash  
batteryml preprocess MATR /path/to/raw/data /path/to/processed/data  
```  
   
To load the processed data, you can use the following Python statement, which will load the resulting `.pkl` file:  
   
```python  
BatteryData.load("/path/to/processed/data/file")  
```  
   
Currently, the `preprocess ARBIN` command is unable to handle all CSV files in the MATR dataset due to errors encountered when processing certain files: "Cannot convert non-finite values (NA or inf) to integer: Error while type casting." We are actively working on inspecting and improving this functionality in future updates.  
   
Thanks again for your feedback and for using our project!
