### ISSUE TITLE
Make the repo a python package.

### ISSUE THREAD

**Issue by CompRhys** [microsoft/BatteryML#9]
Making into a package will enable better interoperability and in principal allow distribution via pypi.

**Comment by aryanxk02** [comment]
This seems like a good idea. Can I start working on this? @CompRhys

**Comment by fingertap** [comment]
Good idea! However, we currently do not organize BatteryML as a Python project because the it hides the preprocessing scripts of the datasets. One option is to include command line tools for data processing, which needs update for new datasets. At this point, we do not host any datasets, and in current form, the inclusion of new datasets are more explicit.

**Comment by fingertap** [comment]
The latest PR should fix this.
